import{r as t,M as $,j as s,u as N,P as _,a as S,b as A,L as B,m as M}from"../assets/proxy.js";import{C as D}from"./CustomCursor.js";import{u as K,N as O}from"./Navigation.js";class T extends t.Component{getSnapshotBeforeUpdate(o){const e=this.props.childRef.current;if(e&&o.isPresent&&!this.props.isPresent){const n=this.props.sizeRef.current;n.height=e.offsetHeight||0,n.width=e.offsetWidth||0,n.top=e.offsetTop,n.left=e.offsetLeft}return null}componentDidUpdate(){}render(){return this.props.children}}function U({children:i,isPresent:o}){const e=t.useId(),n=t.useRef(null),C=t.useRef({width:0,height:0,top:0,left:0}),{nonce:p}=t.useContext($);return t.useInsertionEffect(()=>{const{width:u,height:a,top:h,left:r}=C.current;if(o||!n.current||!u||!a)return;n.current.dataset.motionPopId=e;const c=document.createElement("style");return p&&(c.nonce=p),document.head.appendChild(c),c.sheet&&c.sheet.insertRule(`
          [data-motion-pop-id="${e}"] {
            position: absolute !important;
            width: ${u}px !important;
            height: ${a}px !important;
            top: ${h}px !important;
            left: ${r}px !important;
          }
        `),()=>{document.head.removeChild(c)}},[o]),s.jsx(T,{isPresent:o,childRef:n,sizeRef:C,children:t.cloneElement(i,{ref:n})})}const q=({children:i,initial:o,isPresent:e,onExitComplete:n,custom:C,presenceAffectsLayout:p,mode:u})=>{const a=N(F),h=t.useId(),r=t.useCallback(f=>{a.set(f,!0);for(const v of a.values())if(!v)return;n&&n()},[a,n]),c=t.useMemo(()=>({id:h,initial:o,isPresent:e,custom:C,onExitComplete:r,register:f=>(a.set(f,!1),()=>a.delete(f))}),p?[Math.random(),r]:[e,r]);return t.useMemo(()=>{a.forEach((f,v)=>a.set(v,!1))},[e]),t.useEffect(()=>{!e&&!a.size&&n&&n()},[e]),u==="popLayout"&&(i=s.jsx(U,{isPresent:e,children:i})),s.jsx(_.Provider,{value:c,children:i})};function F(){return new Map}const g=i=>i.key||"";function P(i){const o=[];return t.Children.forEach(i,e=>{t.isValidElement(e)&&o.push(e)}),o}const k=({children:i,custom:o,initial:e=!0,onExitComplete:n,presenceAffectsLayout:C=!0,mode:p="sync",propagate:u=!1})=>{const[a,h]=S(u),r=t.useMemo(()=>P(i),[i]),c=u&&!a?[]:r.map(g),f=t.useRef(!0),v=t.useRef(r),y=N(()=>new Map),[z,L]=t.useState(r),[m,w]=t.useState(r);A(()=>{f.current=!1,v.current=r;for(let d=0;d<m.length;d++){const l=g(m[d]);c.includes(l)?y.delete(l):y.get(l)!==!0&&y.set(l,!1)}},[m,c.length,c.join("-")]);const j=[];if(r!==z){let d=[...r];for(let l=0;l<m.length;l++){const x=m[l],R=g(x);c.includes(R)||(d.splice(l,0,x),j.push(x))}p==="wait"&&j.length&&(d=j),w(P(d)),L(r);return}const{forceRender:b}=t.useContext(B);return s.jsx(s.Fragment,{children:m.map(d=>{const l=g(d),x=u&&!a?!1:r===m||c.includes(l),R=()=>{if(y.has(l))y.set(l,!0);else return;let E=!0;y.forEach(I=>{I||(E=!1)}),E&&(b==null||b(),w(v.current),u&&(h==null||h()),n&&n())};return s.jsx(q,{isPresent:x,initial:!f.current||e?void 0:!1,custom:x?void 0:o,presenceAffectsLayout:C,mode:p,onExitComplete:x?void 0:R,children:d},l)})})};function W({children:i}){const o=K();return s.jsxs("div",{className:"min-h-screen bg-dark relative overflow-hidden",children:[s.jsxs("div",{className:"fixed inset-0 pointer-events-none",children:[s.jsx("div",{className:"absolute top-0 left-1/4 w-96 h-96 bg-turquoise/5 rounded-full blur-[120px]"}),s.jsx("div",{className:"absolute bottom-0 right-1/4 w-[30rem] h-[30rem] bg-midnight/40 rounded-full blur-[150px]"})]}),s.jsx(D,{}),s.jsx(O,{}),s.jsx("main",{className:"relative z-10 min-h-screen pr-72 pl-8 py-12",children:s.jsx(k,{mode:"wait",children:s.jsx(M.div,{initial:{opacity:0,filter:"blur(10px)",y:20},animate:{opacity:1,filter:"blur(0px)",y:0},exit:{opacity:0,filter:"blur(10px)",y:-20},transition:{duration:.8,ease:[.22,1,.36,1]},className:"h-full",children:i},o.pathname)})}),s.jsx(k,{children:s.jsx(M.div,{initial:{opacity:1},animate:{opacity:0},exit:{opacity:1},transition:{duration:1,ease:"easeInOut"},className:"fixed inset-0 pointer-events-none z-40 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-midnight/80 via-dark to-dark",style:{mixBlendMode:"multiply"}},`smoke-${o.pathname}`)})]})}export{k as A,W as L};
